<program> ::=
    <EOF>
    | <line> <program>

<line> ::= <opt-whitespace> <opt-instruction> <opt-whitespace> <opt-comment> "\n"

<opt-label> ::=
    ""
    | <label> ":"

<label> ::=
    <alphanumeric>
    | <alphanumeric> <label>

<instruction> ::=
    <mnemonic>
    | <mnemonic> <whitespace> <opt-operand>

<opt-instruction> ::=
    ""
    | <instruction>

<mnemonic> ::= <alpha> <alpha> <alpha>

<operand> ::=
    <implicit>
    | <accumulator>
    | <immediate>
    | <zeropage>
    | <zeropage-x>
    | <zeropage-y>
    | <relative>
    | <absolute>
    | <absolute-x>
    | <absolute-y>
    | <indirect>
    | <indirect-x>
    | <indirect-y>

<opt-operand> ::=
    ""
    | <operand>

<implicit> ::= ""
<accumulator> ::= "A"
<immediate> ::= "#" <byte>
<zeropage> ::= "$" <byte>
<zeropage-x> ::= <zeropage> ",X"
<zeropage-y> ::= <zeropage> ",Y"
<relative> ::= "*" <signed-decimal-byte>
<absolute> ::= " $" <double-byte>
<absolute-x> ::= <absolute> ",X"
<absolute-y> ::= <absolute> ",Y"
<indirect> ::= "(" <zeropage> ")"
<indirect-x> ::= "(" <zeropage> ",X)"
<indirect-x> ::= "(" <zeropage> "),Y"


<comment> ::= ";" <opt-text>
<opt-comment> ::= "" | <comment>

<whitespace> ::= " " | " " <whitespace>
<opt-whitespace> ::= "" | " " <whitespace>
<opt-text> ::= "" | <text>
<text> ::= <character> | <text><character> 
<byte> ::= <hexadecimal-digit> <hexadecimal-digit>
<double-byte> ::= <byte><byte>
<decimal-digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<hexadecimal-digit> ::= <decimal-digit> | "A" | "B" | "C" | "D" | "E" | "F"
